---
all:
  children:
    db:
      hosts:
        dspace-db:
          ansible_host: 10.0.0.10 # ajuste para o IP real

    backend:
      hosts:
        dspace-backend:
          ansible_host: 10.0.0.11 # ajuste para o IP real

    frontend:
      hosts:
        dspace-frontend:
          ansible_host: 10.0.0.12 # ajuste para o IP real
