---
- name: cria diretorio config
  file:
    path: "{{ dspace_install_dir }}/config"
    state: directory
    owner: "{{ dspace_user }}"
    group: "{{ dspace_group }}"
    mode: "0755"

- name: adiciona tomcat ao grupo dspace para ler configuracoes
  user:
    name: tomcat
    groups: "{{ dspace_group }}"
    append: yes

- name: deploy local.cfg
  template:
    src: local.cfg.j2
    dest: "{{ dspace_install_dir }}/config/local.cfg"
    owner: "{{ dspace_user }}"
    group: "{{ dspace_group }}"
    mode: "0640"
  notify: restart tomcat
